
echo "TC1:" > ../log.txt
./iir ../tests/tc1.json >> ../log.txt
echo "" >> ../log.txt
echo "TC2:" >> ../log.txt
./iir ../tests/tc2.json >> ../log.txt
echo "" >> ../log.txt
echo "TC3:" >> ../log.txt
./iir ../tests/tc3.json >> ../log.txt
echo "" >> ../log.txt
echo "TC4:" >> ../log.txt
./iir ../tests/tc4.json >> ../log.txt
echo "" >> ../log.txt
echo "TC5:" >> ../log.txt
./iir ../tests/tc5.json >> ../log.txt
echo "" >> ../log.txt
echo "TC6:" >> ../log.txt
./iir ../tests/tc6.json >> ../log.txt
echo "" >> ../log.txt
echo "TC7:" >> ../log.txt
./iir ../tests/tc7.json >> ../log.txt

echo "" >> ../log.txt
echo "TC8:" >> ../log.txt
./iir ../tests/bonus_tc8.json >> ../log.txt
echo "" >> ../log.txt
echo "TC9:" >> ../log.txt
./iir ../tests/bonus_tc9.json >> ../log.txt
echo "" >> ../log.txt
echo "TC10:" >> ../log.txt
./iir ../tests/bonus_tc10.json >> ../log.txt
echo "" >> ../log.txt
echo "TC11:" >> ../log.txt
./iir ../tests/bonus_tc11.json >> ../log.txt
echo "" >> ../log.txt
echo "TC12:" >> ../log.txt
./iir ../tests/bonus_tc12.json >> ../log.txt
echo "" >> ../log.txt
echo "TC13:" >> ../log.txt
./iir ../tests/bonus_tc13.json >> ../log.txt
